<?xml version="1.0" encoding="utf-8"?><Database Name="protectdotapp" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=THEILL-PC\SQLEXPRESS;Initial Catalog=protectdotapp;Integrated Security=True" SettingsObjectName="Commanigy.ProtectDotApp.Data.Properties.Settings" SettingsPropertyName="protectdotappConnectionString2" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Packages" Member="Packages">
    <Type Name="Package">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CreatedAt" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="ContentType" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="ContentLength" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="IPAddress" Type="System.String" DbType="NVarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="ZayPayPaymentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="ConfirmationToken" Type="System.String" DbType="NVarChar(32)" CanBeNull="true" />
      <Column Name="Credits" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatedAt" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>